databases:
  - name: faireensemble
    databaseName: faireensemble
    user: faireensemble

services:
  - type: web
    name: faireensemble
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: faireensemble
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
